#!/usr/bin/env bash
# =============================================================================
# scripts/build-bundle.sh
# =============================================================================
# Regenerates engine/engine.bundle.js by concatenating the engine source files
# listed in engine/bundle-manifest.json, in order, each behind a file-boundary
# banner, under an auto-generated header recording the generated date and the
# git blob SHA of every source.
#
# Run by .github/workflows/bundle.yml on any change to an engine source file.
# Do NOT edit engine/engine.bundle.js by hand: edit the source files and let CI
# regenerate it. See ADR-0016 and ADR-0021. Manual local run:
# bash scripts/build-bundle.sh
#
# Dependencies: bash 4+, git, python3 (manifest parsing).
# =============================================================================
set -euo pipefail

MANIFEST="engine/bundle-manifest.json"
OUTPUT="engine/engine.bundle.js"
BANNER="// ============================================================================"

mapfile -t SOURCES < <(python3 -c "import json; [print(s) for s in json.load(open('$MANIFEST'))['sources']]")
[ "${#SOURCES[@]}" -gt 0 ] || { echo "build-bundle: no sources in $MANIFEST" >&2; exit 1; }

{
  echo "$BANNER"
  echo "// engine.bundle.js - Auto-generated engine bundle"
  echo "$BANNER"
  echo "//"
  echo "// Single-file concatenation of the browser-game-engine. AUTO-GENERATED by"
  echo "// scripts/build-bundle.sh via .github/workflows/bundle.yml. Do NOT edit by"
  echo "// hand: edit the engine source files and CI regenerates this file. See"
  echo "// ADR-0016 and ADR-0021 in docs/DECISIONS.md."
  echo "//"
  echo "// Future Claude: fetch THIS file to obtain current engine state. Do not"
  echo "// reconstruct it from individual modules or extract it from old builds."
  echo "//"
  echo "// Generated: $(date -u +%Y-%m-%d)"
  echo "//"
  echo "// Source files (canonical concat order from $MANIFEST; SHAs are git blob"
  echo "// hashes at generation time):"
  for src in "${SOURCES[@]}"; do
    printf '//   %-28s %s\n' "$src" "$(git hash-object "$src")"
  done
  echo "$BANNER"
} > "$OUTPUT"

for src in "${SOURCES[@]}"; do
  { echo ""; echo ""; echo "$BANNER"; echo "// $src"; echo "$BANNER"; echo ""; cat "$src"; } >> "$OUTPUT"
done

echo "build-bundle: regenerated $OUTPUT from ${#SOURCES[@]} source(s)."
